### ISSUE TITLE
Support for repo-level autocompletion (like in Qwen-2.5-Coder)

### ISSUE THREAD

**Issue by kha84** [twinnydotdev/twinny#327] opened 2024-09-23 09:40 UTC
**Is your feature request related to a problem? Please describe.**
Hello there. Few days ago a new bunch of qwen models came out. The one that is particularly interesting is Qwen-2.5-Coder.
What is so special about it is that it support what is called "repository-level code completion". In short, it allows you to put the whole code of your repo in prompt like this:
```
<|repo_name|>{repo_name}
<|file_sep|>{file_path1} 
{file_content1}
<|file_sep|>{file_path2} 
{file_content2}
```
... and it will continue from the end, after `{file_content2}`, considering all the above context. Read more details about it [here](https://github.com/QwenLM/Qwen2.5-Coder?tab=readme-ov-file#4-repository-level-code-completion)

Couple it with a good context size (like 128k) and it promises to become much more knowledgeable AI code autocompletion  tool, rather than conventional fill-in-the middle models.

**Describe the solution you'd like**
I'd like to have an option in Twinny to feed the into the LLM prompt filenames and contents of those files, to accomodate this new appearing feature of LLM models which is "repo-level autocompletion"

**Additional context**
Having said all this, I realize there will be cases, where such models can fail - like if you have a lot of files in your repo, or you short on resources to accommodate the context size of that big. But to me we only can discover all the possible pitfalls after we carefully experience it ourselves.

**Comment by kha84** [comment] 2024-09-23 20:35
That's the million dollar question. There're three options I can see - two are dumb, but easy to implement:

1) let user to specify which files to send. Like to send all the files, which are currently opened by user. Or were recently edited from the same project directory.

2) send all files from the project folder / current repo (might be ought costy)

And there's one more advanced option, but it will be tricky to implement. The idea is to equip some kind of AST parser (specific to the programming language), to figure it out, what other source code files/modules are imported/included to the one, which is currently opened by user. And send only those files which are relevant.

**Comment by kv-gits** [comment] 2024-09-26 07:16
I mentioned it here
https://github.com/twinnydotdev/twinny/issues/320

**Comment by rjmacarthy** [comment] 2024-09-26 12:15
I've been experimenting with this, the issue is that the prompt does not contain the suffix, so it will only generate code from suffix and has no knowledge of code below the cursor.  It works really well, and I will make a PR but I think fill-in-middle file completion is better until this issue is addressed in the future.

**Comment by rjmacarthy** [comment] 2024-09-26 18:11
Now there is a checkbox in the provider in `v3.17.18` which enables/disabled repository level completions for fim providers.

**Closed** 2024-09-26 18:11 UTC

**Comment by kha84** [comment] 2024-09-26 18:13
You're the start! I'll give everything a proper trial and report back with my findings / comments.
