### ISSUE TITLE
Not working with dev containers?

### ISSUE THREAD

**Issue by vitobotta** [twinnydotdev/twinny#419] opened 2024-12-10 22:45 UTC
**Describe the bug**
Hi! I configured Twinny with LMStudio and it's working fine in local mode, but it doesn't work when I switch to a dev container. The progress bar in the panel moves horizontally indefinitely and I can't configure providers nor do anything else. Any suggestions?

**To Reproduce**
Try and use Twinny with VSCode in a dev container

**Expected behavior**
Autocompletion and chat should work just as in local mode

**Screenshots**

**Logging**
I don't know how to produce logs  because I cannot interact with the extension at all.

**API Provider**
Can't configure provider when in dev container

**Chat or Auto Complete?**
Both

**Model Name**
Tried with several models

**Desktop (please complete the following information):**
 - OS: macOS Sequoia, latest version

**Additional context**

**Comment by rjmacarthy** [comment] 2024-12-11 09:08
Duplicate of https://github.com/twinnydotdev/twinny/issues/356

**Closed by rjmacarthy** 2024-12-11 09:08 UTC
Labels: bug, help wanted, question
