### ISSUE TITLE
"Sorry, I don’t understand. Please try again." - invalid option rope_frequency_base

### ISSUE THREAD

**Issue by machisuji** [twinnydotdev/twinny#313] opened 2024-09-13 12:28 UTC
**Describe the bug**
I just wanted to get started with twinny. I followed all the instructions, but twinny's chat doesn't work.
No matter what you say, it responds that it doesn't understand.

The ollama logs point to why:

```
time=2024-09-13T12:15:00.064Z level=WARN source=types.go:509 msg="invalid option provided" option=rope_frequency_base
```

**To Reproduce**
1. Install ollama
2. `ollama pull codellama:7b-instruct`
3. `ollama pull codellama:7b-code`
4. Install twinny in vscode
5. Try chatting

**Expected behavior**
Twinny should work and show a response

**Screenshots**
![image](https://github.com/user-attachments/assets/8e07be0d-dedf-4ae4-86ca-59bb0634387e)

**Logging**
Rnable logging in the extension settings if not already enabled (you may need to restart vscode if you don't see logs).  Proivide the log with the report.

```
2024-09-13 15:07:41.088 [error] [Extension Host] Error parsing JSON: TypeError: Cannot read properties of undefined (reading '0')
	at getChatDataFromProvider (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:73226:27)
	at ChatService.onStreamData (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:84602:22)
	at onData (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:84894:41)
	at Object.transform (/home/mk/.vscode-server/extensions/rjmacarthy.twinny-3.16.2-linux-x64/out/index.js:73744:26)
	at ensureIsPromise (node:internal/webstreams/util:185:19)
	at transformStreamDefaultControllerPerformTransform (node:internal/webstreams/transformstream:515:18)
	at node:internal/webstreams/transformstream:560:16
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**API Provider**
Ollama

**Chat or Auto Complete?**
* chat
* FIM works just fine it seems!

**Model Name**
`codellama:7b-code` and `codellama:7b-instruct`

**Desktop (please complete the following information):**
 - OS: Windows 11 with WSL2 (ollama running on Linux)
 - VSCode 1.93.1
 - Twinny v3.16.2

**Additional context**

**Comment by machisuji** [comment] 2024-09-13 12:30
I suppose the default llamacode models just don't support the rope_frequency_base option (anymore?).
But if these models are the default to be used according to the docs, then ideally twinny would not use that option to make it work.

Is there perhaps a way for a user to remove that option themselves from the requests made by twinny?

**Comment by dpkirchner** [comment] 2024-09-14 14:34
I dug in to this and chatted with someone working on ollama and it looks like `rope_frequency_base` is a red herring. The problem appears to be somewhere else. Specifically, the extension is trying to get completion content from an object but the content is blank -- when I ask a question, no matter what question, the response that is sent to `getCompletionContent` is `{"completion":"","data":{"language":{"langName":"Go","fileExtensions":[".go"],"syntaxComments":{"start":"/","end":"/"}},"languageId":"go"},"type":""}` (in a go program). Unfortunately I haven't been able to get very far debugging it.

**Comment by Bombfuse** [comment] 2024-09-17 00:49
I've also tried previous ollama versions down to 0.3.7 and was unable to get those to work as well

**Comment by rjmacarthy** [comment] 2024-09-18 09:49
Seems to be duplicate of https://github.com/twinnydotdev/twinny/issues/315

**Closed by rjmacarthy** 2024-09-18 09:49 UTC
