### ISSUE TITLE
Twinny Extension won't load.    Lancedb module missing

### ISSUE THREAD

**Issue by gpinkham** [twinnydotdev/twinny#365] opened 2024-11-01 01:47 UTC
**Describe the bug**
Started just tonight.   The Twinny extension won't finish loading.    I get a "progress" bar just below the icon toolbar and nothing else in the chat dialog for Twinny.   There's also a clock badge on the twinny icon in the left nav..   trying to execute any Twinny commands from the command palette returns a command not found.   
<img width="300" alt="image" src="https://github.com/user-attachments/assets/07cdf086-d53d-4886-a0b3-2bfae0d609ea">

I also tried to disable/reenable.   tried uninstall/reinstall.     everything just lands me with no Twinny extension loaded

**To Reproduce**
load VSCode..  

**Expected behavior**
Usable Twinny UI

**Screenshots**
<img width="300" alt="image" src="https://github.com/user-attachments/assets/5477c9e7-725b-47c1-86aa-fbc25a256de8">

**Logging**
didn't know about the logging.  will enable and try to find the logs 

**API Provider**
Ollama

**Chat or Auto Complete?**
Extension itself.  

**Model Name**
Provide the model name you are using e.g `codellama:7b-code` or `codellama:7b-instruct`

**Desktop (please complete the following information):**
 - Osx 15.1
 - Chrome
 - VSCode 1.95.1
 - Twinny v3.17.31

**Additional context**

**Comment by gpinkham** [comment] 2024-11-01 01:50
Looks like I'm missing a module. 

2024-10-31 21:39:33.998 [error] Error: Cannot find module '@lancedb/lancedb-darwin-arm64'
Require stack:
- /Users/gpinkham/.vscode/extensions/rjmacarthy.twinny-3.17.31-darwin-arm64/out/index.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Function.n._resolveFilename (node:electron/js2c/utility_init:2:16068)
    at Function.t._resolveFilename (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22715)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at Function.c._load (node:electron/js2c/node_init:2:16955)
    at Function.e._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
    at Function.t._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
    at Function.i._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at node_modules/@lancedb/lancedb/dist/native.js (/Users/gpinkham/.vscode/extensions/rjmacarthy.twinny-3.17.31-darwin-arm64/out/index.js:19695:33)
    at __require (/Users/gpinkham/.vscode/extensions/rjmacarthy.twinny-3.17.31-darwin-arm64/out/index.js:12:50)
    at node_modules/@lancedb/lancedb/dist/index.js (/Users/gpinkham/.vscode/extensions/rjmacarthy.twinny-3.17.31-darwin-arm64/out/index.js:34707:23)
    at __require (/Users/gpinkham/.vscode/extensions/rjmacarthy.twinny-3.17.31-darwin-arm64/out/index.js:12:50)
    at Object.<anonymous> (/Users/gpinkham/.vscode/extensions/rjmacarthy.twinny-3.17.31-darwin-arm64/out/index.js:71440:23)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at Function.c._load (node:electron/js2c/node_init:2:16955)
    at Function.e._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
    at Function.t._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
    at Function.i._load (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at z_.xb (file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23753)

**Comment by gpinkham** [comment] 2024-11-01 02:11
I think this is a dupe of https://github.com/twinnydotdev/twinny/issues/364
I'll leave this here for now since I have the logs in this ticket      But feel free to close as dupe.

**Comment by rjmacarthy** [comment] 2024-11-01 12:25
Thanks for reporting, let's close this as it's a duplicate of https://github.com/twinnydotdev/twinny/issues/364.

Many thanks!

**Closed by rjmacarthy** 2024-11-01 12:25 UTC
